/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ejercicios;
import java.util.ArrayList;
import java.util.HashSet;
/**
 *
 * @author azteca
 */


public class frmAgenda extends javax.swing.JFrame {

   private ArrayList<clsPersona>lstPersonas = new ArrayList<clsPersona>();
   
    public frmAgenda() {
       initComponents();
        setLocationRelativeTo(null);
        lstPersonas = new ArrayList<clsPersona>();
        cargarPersona();
    }
    
    private void cargarPersona(){
        clsPersona p = new clsPersona();
        p.setAnio("1990");
        p.setCelular("7878123");
        p.setCodigo(5);
        p.setDia("18");
        p.setEmail("email");
        p.setEstado('A');
        p.setMes("1");
        p.setNombre("Charlie");
        p.setSexo('M');
        p.setTelefonoFijo("23432432");
        p.setTipoPersona("Alumno");
        lstPersonas.add(p);
        clsPersona pe = new clsPersona();
        pe.setAnio("1890");
        pe.setCelular("6568123");
        pe.setCodigo(10);
        pe.setDia("15");
        pe.setEmail("email");
        pe.setEstado('I');
        pe.setMes("3");
        pe.setNombre("Juan");
        pe.setSexo('F');
        pe.setTelefonoFijo("872345");
        pe.setTipoPersona("Docente");
        lstPersonas.add(pe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVerListaContacto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ADMINISTRAR AGENDA DE CONTACTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnVerListaContacto.setText("VER LISTA DE CONTACTO");
        btnVerListaContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListaContactoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerListaContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 140));
        jPanel1.getAccessibleContext().setAccessibleName("");

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 173, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerListaContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListaContactoActionPerformed
     frmListarContacto ventana = new frmListarContacto(lstPersonas);
     ventana.setVisible(true);
    }//GEN-LAST:event_btnVerListaContactoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerListaContacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
